image: python:3.6

stages:
  - test
  - install   

run_unit_tests_python_3:
  stage: test
  script:
    - pip install libgl1
    - pip install -r requirements.txt
    - python setup.py test


run_install_of_package:
  stage: install
  script:
    - python setup.py install
