image: python:3.6.6-windowsservercore-1709

variables:
    PYPI_USER: SECURE
    PYPI_PASSWORD: SECURE

stages:
  - test
  - install   
  - mirror
  - deploy
  
before_script:
    - pip install pypandoc
         
run_unit_tests:
  stage: test
  tags:
    - linux
    - python
  script:
    - python setup.py test
    
run_install_of_package:
  stage: install
  tags:
    - linux
    - python
  script:
    - python setup.py install

github_mirror:
  stage: mirror
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags) v1.0.0
  script:
    - git checkout master
    - git pull origin master
    - git push https://Ecklebe:$GITHUB_OAUTH_TOKEN@github.com/Ecklebe/pylibcklb.git master --force

pypi_dist:
  stage: deploy
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags) v1.0.0
  script:
    - echo "[server-login]" >> ~/.pypirc
    - echo "username=" ${PYPI_USER} >> ~/.pypirc
    - echo "password=" ${PYPI_PASSWORD} >> ~/.pypirc
    #- sudo dpkg -i https://github.com/jgm/pandoc/releases/download/2.1.1/pandoc-2.1.1-linux.tar.gz
    - python setup.py register sdist upload