image: python:3.6

stages:
  - test
  - install   
  - mirror
         
run_unit_tests:
  stage: test
  tags:
    - linux
    - python
  script:
    - python setup.py test
    
run_install_of_package:
  stage: install
  tags:
    - linux
    - python
  script:
    - python setup.py install

github_mirror:
  stage: mirror
  only:
    - master
  script:
    - git checkout master
    - git pull origin master
    - git push https://Ecklebe:$GITHUB_OAUTH_TOKEN@github.com/Ecklebe/pylibcklb.git master --force