image: alpine:3.6

stages:
  - requirements
  - test
  - install   

installation_of_requirements:
  stage: requirements
  script:
    - uname -i
    - apk update && apk add python python-dev python-pip
    - pip install SIP
    - pip install pyqt5
    - pip install -r requirements.txt

run_unit_tests_python_3:
  stage: test
  script:
    - python setup.py test


run_install_of_package:
  stage: install
  script:
    - python setup.py install
