image: python:3.6

stages:
  - test
  - install   

before_script:
  - python --versions
  - pip install -r requirements.txt

run_unit_tests_python_3:
  stage: test
  tags:
    - linux
    - python
  script:
    - python setup.py test


run_install_of_package:
  stage: install
  tags:
    - linux
    - python
  script:
    - python setup.py install
